### ISSUE TITLE
Can't load rubyzip ...?

### ISSUE THREAD

**Issue by phillipadsmith** [imanel/odt2html#2]
Possibly obvious issue here, but in my pre-coffee state I'm stumpted:

```
/Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/gems/odt2html-0.1.1/lib/odt2html.rb:3:in `require': cannot load such file -- zip/zip (LoadError)
    from /Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/gems/odt2html-0.1.1/lib/odt2html.rb:3:in `<top (required)>'
    from /Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/gems/odt2html-0.1.1/bin/odt2html:6:in `require'
    from /Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/gems/odt2html-0.1.1/bin/odt2html:6:in `<top (required)>'
    from /Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/bin/odt2html:23:in `load'
    from /Users/phillipadsmith/Development/beautiful-rising-doc-bot/_vendor/ruby/2.1.0/bin/odt2html:23:in `<main>'
```

Trying with a system-wide install, same thing:

```
/Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- zip/zip (LoadError)
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/odt2html-0.1.1/lib/odt2html.rb:3:in `<top (required)>'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/odt2html-0.1.1/bin/odt2html:6:in `<top (required)>'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/bin/odt2html:23:in `load'
    from /Users/phillipadsmith/.rbenv/versions/2.1.2/bin/odt2html:23:in `<main>'
```

Any pointers appreciated. :)

Phillip.

**Comment by tomash** [comment]
rubygems or github version? new rubyzip has been included in #1, but I'm not sure if @imanel released a new gem version after that

**Comment by tomash** [comment]
yep, it's 0.1.1, released back in 2011. if you can, try github master branch and see of the issue persists.

**Comment by imanel** [comment]
Pushed version 0.2.0 - should fix this problem. It's strange feeling to release new version after 4 years ;)

**Comment by phillipadsmith** [comment]
@imanel That's working beautifully, thanks! :)
